language: go

go:
  - 1.5
  - 1.6
  - 1.7

script:
  - mkdir -p $GOPATH/src/github.com/customerio
  - git clone -b master https://github.com/customerio/gospec.git $GOPATH/src/github.com/customerio/gospec
  - go test -v

services:
  - redis-server

notifications:
  email:
    on_success: change
    on_failure: always
    on_start: false

