language: go

go:
  - 1.5
  - 1.6
  - 1.7

script:
  - go get github.com/customerio/gospec
  - cd $GOPATH/src/github.com/customerio/gospec
  - git checkout master
  - cd -
  - go test -v

services:
  - redis-server

notifications:
  email:
    on_success: change
    on_failure: always
    on_start: false

